### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'str'. `np.str` was a deprecated alias for the builtin `str`. To avoid this error in existing code, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here. The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:     https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'std'?

### ISSUE THREAD

**Issue by monajalal** [PyramidHe/PVNet#3]
@PyramidHe 

Matteo 

How did you resolve these?

```
(new-pvnet) mona@ada:~/new-pvnet/PVNet$ python run.py --type linemod cls_type cat
/home/mona/new-pvnet/PVNet/lib/datasets/linemod/linemod_to_coco.py:133: FutureWarning: In the future `np.str` will be defined as the corresponding NumPy scalar.
  inds = np.loadtxt(os.path.join(data_root, cls, split + '.txt'), np.str)
Traceback (most recent call last):
  File "/home/mona/new-pvnet/PVNet/run.py", line 308, in <module>
    globals()['run_'+args.type]()
  File "/home/mona/new-pvnet/PVNet/run.py", line 171, in run_linemod
    linemod_to_coco.linemod_to_coco(cfg)
  File "/home/mona/new-pvnet/PVNet/lib/datasets/linemod/linemod_to_coco.py", line 305, in linemod_to_coco
    _linemod_to_coco(cfg.cls_type, 'train')
  File "/home/mona/new-pvnet/PVNet/lib/datasets/linemod/linemod_to_coco.py", line 290, in _linemod_to_coco
    img_id, ann_id = record_real_ann(model_meta, img_id, ann_id, images, annotations)
  File "/home/mona/new-pvnet/PVNet/lib/datasets/linemod/linemod_to_coco.py", line 133, in record_real_ann
    inds = np.loadtxt(os.path.join(data_root, cls, split + '.txt'), np.str)
  File "/home/mona/.local/lib/python3.10/site-packages/numpy/__init__.py", line 324, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'str'.
`np.str` was a deprecated alias for the builtin `str`. To avoid this error in existing code, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'std'?

```

**Comment by monajalal** [comment]
replaced np.str w str let me know if that makes sense to you
```
(new-pvnet) mona@ada:~/new-pvnet/PVNet$ rg "np\.str" -t py
lib/datasets/linemod/linemod_to_coco.py
79:    inds = np.loadtxt(os.path.join('data/linemod', cls, 'test_occlusion.txt'), np.str)
133:    inds = np.loadtxt(os.path.join(data_root, cls, split + '.txt'), np.str)
(new-pvnet) mona@ada:~/new-pvnet/PVNet$ vi lib/datasets/linemod/linemod_to_coco.py
(new-pvnet) mona@ada:~/new-pvnet/PVNet$ python run.py --type linemod cls_type cat
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 177/177 [00:00<00:00, 2419.70it/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10000/10000 [00:15<00:00, 659.48it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10000/10000 [00:03<00:00, 2755.55it/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1002/1002 [00:00<00:00, 3296.57it/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1187/1187 [00:00<00:00, 3381.21it/s]
(new-pvnet) mona@ada:~/new-pvnet/PVNet$ 
```
