### ISSUE TITLE
weird results for tless evaluate

### ISSUE THREAD

**Issue by monajalal** [PyramidHe/PVNet#6]
I get this error for tless

```

(new-pvnet) mona@ada:~/new-pvnet/PVNet$ python run.py --type evaluate --cfg_file configs/tless/tless_01.yaml
/home/mona/anaconda3/envs/new-pvnet/lib/python3.10/site-packages/imgaug/imgaug.py:184: DeprecationWarning: Function `ContrastNormalization()` is deprecated. Use `imgaug.contrast.LinearContrast` instead.
  warn_deprecated(msg, stacklevel=3)
loading annotations into memory...
Done (t=3.73s)
creating index...
index created!
loading annotations into memory...
Done (t=3.82s)
creating index...
index created!
Traceback (most recent call last):
  File "/home/mona/new-pvnet/PVNet/run.py", line 308, in <module>
    globals()['run_'+args.type]()
  File "/home/mona/new-pvnet/PVNet/run.py", line 74, in run_evaluate
    evaluator = make_evaluator(cfg)
  File "/home/mona/new-pvnet/PVNet/lib/evaluators/make_evaluator.py", line 19, in make_evaluator
    return _evaluator_factory(cfg)
  File "/home/mona/new-pvnet/PVNet/lib/evaluators/make_evaluator.py", line 11, in _evaluator_factory
    evaluator = imp.load_source(module, path).Evaluator(cfg.result_dir)
  File "lib/evaluators/tless_test/pvnet.py", line 42, in __init__
    model_info = yaml.load(open(os.path.join(model_dir, 'models_info.yml')))
TypeError: load() missing 1 required positional argument: 'Loader'


```

I resolved it using

```
        #model_info = yaml.load(open(os.path.join(model_dir, 'models_info.yml')))
        with open(os.path.join(model_dir, 'models_info.yml')) as f:
            model_info = yaml.safe_load(f)

```

Does that make sense to you?

When I got the evaluation, all metrics are reported as zero except adi, and I am not sure what that's supposed to be.

could you please share the result of running this command on your end?

```
(new-pvnet) mona@ada:~/new-pvnet/PVNet$ python run.py --type evaluate --cfg_file configs/tless/tless_01.yaml
/home/mona/anaconda3/envs/new-pvnet/lib/python3.10/site-packages/imgaug/imgaug.py:184: DeprecationWarning: Function `ContrastNormalization()` is deprecated. Use `imgaug.contrast.LinearContrast` instead.
  warn_deprecated(msg, stacklevel=3)
loading annotations into memory...
Done (t=3.78s)
creating index...
index created!
loading annotations into memory...
Done (t=3.74s)
creating index...
index created!
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2927/2927 [03:22<00:00, 14.48it/s]
vsd metric: 0.0
adi metric: 0.00033178500331785003
5 cm 5 degree metric: 0.0


```

**Comment by monajalal** [comment]
@PyramidHe  where should the tless model exactly be located?

l have these
```
(new-pvnet) mona@ada:~/new-pvnet/PVNet$ ls data
total 16K
lrwxrwxrwx  1 mona mona   33 Nov 27 15:37 occlusion_linemod -> /data2/data/BOP/OCCLUSION_LINEMOD
lrwxrwxrwx  1 mona mona   22 Nov 27 15:37 cache -> /data2/data/BOP/cache/
lrwxrwxrwx  1 mona mona   42 Nov 27 15:37 tless -> /data2/data/BOP/tless/tless_dataset/tless/
lrwxrwxrwx  1 mona mona   28 Nov 27 15:39 linemod_orig -> /data2/data/BOP/LINEMOD_ORIG
lrwxrwxrwx  1 mona mona   26 Nov 27 15:40 linemod -> /data2/data/BOP/lm/LINEMOD
lrwxrwxrwx  1 mona mona   31 Nov 27 15:41 sun -> /data2/data/SUN2012pascalformat
drwxrwxr-x  3 mona mona 4.0K Nov 27 16:20 result
drwxrwxr-x  4 mona mona 4.0K Nov 28 16:12 .
drwxrwxr-x  3 mona mona 4.0K Nov 28 17:00 model
drwxrwxr-x 12 mona mona 4.0K Nov 28 17:07 ..
```

and

```
(new-pvnet) mona@ada:~/new-pvnet/PVNet$ ls /data2/data/BOP/tless/tless_dataset/tless/
total 1.1M
-rw-rw-r--  1 mona mona 856K Feb 18  2020 bg_imgs.npy
-rw-rw-r--  1 mona mona 235K Feb 18  2020 poses.npy
drwxrwxr-x  2 mona mona 4.0K Feb 18  2020 farthest
drwxrwxr-x 22 mona mona 4.0K Feb 18  2020 renders
drwxrwxr-x 22 mona mona 4.0K Feb 18  2020 test_primesense
drwxrwxr-x  7 mona mona 4.0K Feb 18  2020 .
drwxrwxr-x  3 mona mona 4.0K Feb 18  2020 train_primesense
drwxrwxr-x  3 mona mona 4.0K Nov 20 09:09 ..
drwxrwxr-x  2 mona mona 4.0K Nov 20 09:27 models_cad

```
